DROP DATABASE IF EXISTS CRISPIM;

-- CRIAÇÃO DO BANCO DE DADOS

CREATE DATABASE CRISPIM DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;

USE CRISPIM;

-- CRIAÇÃO DAS TABELAS DO BANCO DE DADOS

CREATE TABLE ESTADO(
    ID INT NOT NULL AUTO_INCREMENT UNIQUE
    ,NOME VARCHAR(200) NOT NULL
    ,SIGLA CHAR(2) NOT NULL
    ,ATIVO CHAR(1) NOT NULL DEFAULT 'S' CHECK(ATIVO IN('S', 'N'))
    ,DATA_CADASTRO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
    ,CONSTRAINT PK_ESTADO PRIMARY KEY ESTADO(ID)
);

CREATE TABLE CIDADE(
    ID INT NOT NULL AUTO_INCREMENT UNIQUE
    ,NOME VARCHAR(200) NOT NULL
    ,DATA_CADASTRO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
    ,ATIVO CHAR(1) NOT NULL DEFAULT 'S' CHECK(ATIVO IN('S', 'N'))
    ,ESTADO_ID INT NOT NULL
    ,CONSTRAINT PK_CIDADE PRIMARY KEY CIDADE(ID)
    ,CONSTRAINT FK_CIDADE_ESTADO FOREIGN KEY (ESTADO_ID) REFERENCES ESTADO(ID)
);

CREATE TABLE CATEGORIA_PRODUTO(
    ID INT NOT NULL AUTO_INCREMENT UNIQUE
    ,NOME VARCHAR(100) NOT NULL
    ,DATA_CADASTRO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
    ,ATIVO CHAR(1) NOT NULL DEFAULT 'S' CHECK(ATIVO IN('S', 'N'))
    ,CONSTRAINT PK_CATEGORIA_PRODUTO PRIMARY KEY CATEGORIA(ID)
);

CREATE TABLE PRODUTO(
    ID INT NOT NULL AUTO_INCREMENT UNIQUE
    ,NOME VARCHAR(200) NOT NULL
    ,PRECO DECIMAL(10,2) NOT NULL
    ,DATA_CADASTRO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
    ,ATIVO CHAR(1) NOT NULL DEFAULT 'S' CHECK(ATIVO IN('S', 'N'))
    ,CATEGORIA_ID INT
    ,CONSTRAINT PK_PRODUTO PRIMARY KEY PRODUTO(ID)
    ,CONSTRAINT FK_CATEGORIA_PRODUTO FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIA_PRODUTO(ID)
);


CREATE TABLE CLIENTE(
    ID INT NOT NULL AUTO_INCREMENT UNIQUE
    ,NOME VARCHAR(200) NOT NULL
    ,CPF VARCHAR(20) NOT NULL UNIQUE
    ,TELEFONE VARCHAR(20) NOT NULL
    ,ENDERECO VARCHAR(200) NOT NULL
    ,NUMERO VARCHAR(10) NOT NULL
    ,DATA_CADASTRO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
    ,ATIVO CHAR(1) NOT NULL DEFAULT 'S' CHECK(ATIVO IN('S', 'N'))
    ,CIDADE_ID INT NOT NULL
    ,CONSTRAINT PK_CLIENTE PRIMARY KEY CLIENTE(ID)
    ,CONSTRAINT FK_CIDADE_CLIENTE FOREIGN KEY (CIDADE_ID) REFERENCES CIDADE(ID)
);

CREATE TABLE VENDA(
    ID INT NOT NULL AUTO_INCREMENT UNIQUE
    ,DATA_HORA DATETIME DEFAULT CURRENT_TIMESTAMP
    ,CLIENTE_ID INT NOT NULL
    ,CONSTRAINT PK_VENDA PRIMARY KEY VENDA(ID)
    ,CONSTRAINT FK_VENDA_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(ID)
);

CREATE TABLE ITEM_VENDA(
    ID INT NOT NULL AUTO_INCREMENT UNIQUE
    ,PRODUTO_ID INT NOT NULL
    ,PRECO_UNITARIO DECIMAL(10,2)
    ,QUANTIDADE INT NOT NULL
    ,DATA_HORA DATETIME DEFAULT CURRENT_TIMESTAMP
    ,VENDA_ID INT NOT NULL
    ,TOTAL DECIMAL(10,2) AS (PRECO_UNITARIO * QUANTIDADE) STORED
    ,CONSTRAINT PK_ITEM_VENDA PRIMARY KEY ITEM_VENDA(ID)
    ,CONSTRAINT FK_PRODUTO_ID FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTO(ID)
    ,CONSTRAINT FK_VENDA_ID FOREIGN KEY (VENDA_ID) REFERENCES VENDA(ID)
);

CREATE TABLE FORMA_DE_PAGAMENTO(
    ID INT NOT NULL AUTO_INCREMENT UNIQUE
    ,NOME VARCHAR(100) NOT NULL
    ,DATA_CADASTRO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
    ,ATIVO CHAR(1) NOT NULL DEFAULT 'S' CHECK(ATIVO IN('S', 'N'))
    ,CONSTRAINT PK_FPAGAMENTO PRIMARY KEY FORMA_DE_PAGAMENTO(ID)
);

CREATE TABLE PAGAMENTO(
    ID INT NOT NULL AUTO_INCREMENT UNIQUE
    ,STATUS_PAGAMENTO VARCHAR(20) NOT NULL
    ,DATA_HORA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
    ,TOTAL_BRUTO INT NOT NULL
    ,DESCONTO INT
    ,TOTAL_LIQUIDO INT NOT NULL
    ,FPAGAMENTO_ID INT NOT NULL
    ,VENDA_ID INT NOT NULL
    ,CONSTRAINT PK_PAGAMENTO PRIMARY KEY PAGAMENTO(ID)
    ,CONSTRAINT STATUS_PAGAMENTO_PADRAO CHECK(STATUS_PAGAMENTO IN('PENDENTE', 'PAGO'))
    ,CONSTRAINT FK_PAGAMENTO_FPAGAMENTO FOREIGN KEY (FPAGAMENTO_ID) REFERENCES FORMA_DE_PAGAMENTO(ID)
    ,CONSTRAINT FK_PAGAMENTO_VENDA FOREIGN KEY (VENDA_ID) REFERENCES VENDA(ID)
);


-- ALIMENTANDO O BANCO

-- ESTADOS

INSERT INTO ESTADO (NOME, SIGLA) VALUES ('RIO GRANDE DO SUL', 'RS');
INSERT INTO ESTADO (NOME, SIGLA) VALUES ('RIO GRANDE DO SUL', 'RS');
INSERT INTO ESTADO (NOME, SIGLA) VALUES ('PARANÁ', 'PR');
INSERT INTO ESTADO (NOME, SIGLA) VALUES ('SANTA CATARINA', 'SC');
INSERT INTO ESTADO (NOME, SIGLA) VALUES ('ESPIRITO SANTO', 'ES');
INSERT INTO ESTADO (NOME, SIGLA) VALUES ('SÃO PAULO', 'SP');
INSERT INTO ESTADO (NOME, SIGLA) VALUES ('RIO DE JANEIRO', 'RJ');
INSERT INTO ESTADO (NOME, SIGLA) VALUES ('MINAS GERAIS', 'MG');
INSERT INTO ESTADO (NOME, SIGLA) VALUES ('MATO GROSSO DO SUL', 'MS');
INSERT INTO ESTADO (NOME, SIGLA) VALUES ('MATO GROSSO', 'MT');
INSERT INTO ESTADO (NOME, SIGLA) VALUES ('TOCANTINS', 'TO');
INSERT INTO ESTADO (NOME, SIGLA) VALUES ('AMAZONAS', 'AM');
INSERT INTO ESTADO (NOME, SIGLA) VALUES ('GOIÁS', 'GO');
INSERT INTO ESTADO (NOME, SIGLA) VALUES ('RONDONIA', 'RO');
INSERT INTO ESTADO (NOME, SIGLA) VALUES ('ACRE', 'AC');
INSERT INTO ESTADO (NOME, SIGLA) VALUES ('RORAIMA', 'RR');
INSERT INTO ESTADO (NOME, SIGLA) VALUES ('PARÁ', 'PA');
INSERT INTO ESTADO (NOME, SIGLA) VALUES ('AMAPÁ', 'AP');
INSERT INTO ESTADO (NOME, SIGLA) VALUES ('MARANHÃO', 'MA');
INSERT INTO ESTADO (NOME, SIGLA) VALUES ('PIAUÍ', 'PI');
INSERT INTO ESTADO (NOME, SIGLA) VALUES ('RIO GRANDE DO NORTE', 'RN');
INSERT INTO ESTADO (NOME, SIGLA) VALUES ('PARAÍBA', 'PB');
INSERT INTO ESTADO (NOME, SIGLA) VALUES ('PERNAMBUCO', 'PE');
INSERT INTO ESTADO (NOME, SIGLA) VALUES ('ALAGOAS', 'AL');
INSERT INTO ESTADO (NOME, SIGLA) VALUES ('SERGIPE', 'SE');
INSERT INTO ESTADO (NOME, SIGLA) VALUES ('BAHIA', 'BA');

-- CATEGORIAS DE PRODUTOS

INSERT INTO CATEGORIA_PRODUTO (NOME) VALUES ('LANCHE');
INSERT INTO CATEGORIA_PRODUTO (NOME) VALUES ('LANCHE GOURMET');
INSERT INTO CATEGORIA_PRODUTO (NOME) VALUES ('PORÇÃO');
INSERT INTO CATEGORIA_PRODUTO (NOME) VALUES ('COMBO');
INSERT INTO CATEGORIA_PRODUTO (NOME) VALUES ('SUCO');
INSERT INTO CATEGORIA_PRODUTO (NOME) VALUES ('BEBIDA');

-- CIDADES
INSERT INTO CIDADE(NOME, ESTADO_ID) VALUES ('TERRA RICA', 1);
INSERT INTO CIDADE(NOME, ESTADO_ID) VALUES ('PARANAVAÍ', 1);
INSERT INTO CIDADE(NOME, ESTADO_ID) VALUES ('MARINGÁ', 1);
INSERT INTO CIDADE(NOME, ESTADO_ID) VALUES ('CURITIBA', 1);
INSERT INTO CIDADE(NOME, ESTADO_ID) VALUES ('PORTO ALEGRE', 2);
INSERT INTO CIDADE(NOME, ESTADO_ID) VALUES ('FLORIANÓPOLIS', 3);
INSERT INTO CIDADE(NOME, ESTADO_ID) VALUES ('ITAJAÍ', 3);
INSERT INTO CIDADE(NOME, ESTADO_ID) VALUES ('BALNEÁRIO CAMBORIÚ', 3);
INSERT INTO CIDADE(NOME, ESTADO_ID) VALUES ('SÃO PAULO', 5);
INSERT INTO CIDADE(NOME, ESTADO_ID) VALUES ('SANTO ANASTÁCIO', 5);
INSERT INTO CIDADE(NOME, ESTADO_ID) VALUES ('VITÓRIA', 4);
INSERT INTO CIDADE(NOME, ESTADO_ID) VALUES ('RIO DE JANEIRO', 6);
INSERT INTO CIDADE(NOME, ESTADO_ID) VALUES ('BELO HORIZONTE', 7);
INSERT INTO CIDADE(NOME, ESTADO_ID) VALUES ('CAMPO GRANDE', 8);
INSERT INTO CIDADE(NOME, ESTADO_ID) VALUES ('CUIABÁ', 9);
INSERT INTO CIDADE(NOME, ESTADO_ID) VALUES ('PALMAS', 10);
INSERT INTO CIDADE(NOME, ESTADO_ID) VALUES ('MANAUS', 11);
INSERT INTO CIDADE(NOME, ESTADO_ID) VALUES ('GOIANIA', 12);
INSERT INTO CIDADE(NOME, ESTADO_ID) VALUES ('PORTO VELHO', 13);
INSERT INTO CIDADE(NOME, ESTADO_ID) VALUES ('RIO BRANCO', 14);
INSERT INTO CIDADE(NOME, ESTADO_ID) VALUES ('BOA VISTA', 15);
INSERT INTO CIDADE(NOME, ESTADO_ID) VALUES ('BELÉM', 16);
INSERT INTO CIDADE(NOME, ESTADO_ID) VALUES ('MACAPÁ', 17);
INSERT INTO CIDADE(NOME, ESTADO_ID) VALUES ('SÃO LUÍS', 18);
INSERT INTO CIDADE(NOME, ESTADO_ID) VALUES ('TERESINA', 19);
INSERT INTO CIDADE(NOME, ESTADO_ID) VALUES ('NATAL', 20);
INSERT INTO CIDADE(NOME, ESTADO_ID) VALUES ('JOÃO PESSOA', 21);
INSERT INTO CIDADE(NOME, ESTADO_ID) VALUES ('RECIFE', 22);
INSERT INTO CIDADE(NOME, ESTADO_ID) VALUES ('MACEIÓ', 23);
INSERT INTO CIDADE(NOME, ESTADO_ID) VALUES ('ARACAJU', 24);
INSERT INTO CIDADE(NOME, ESTADO_ID) VALUES ('SALVADOR', 26);

-- FORMA DE PAGAMENTO

INSERT INTO FORMA_DE_PAGAMENTO(NOME) VALUES ('DÉBITO');
INSERT INTO FORMA_DE_PAGAMENTO(NOME) VALUES ('CRÉDITO');
INSERT INTO FORMA_DE_PAGAMENTO(NOME) VALUES ('DINHEIRO');
INSERT INTO FORMA_DE_PAGAMENTO(NOME) VALUES ('PIX');

-- PRODUTOS

INSERT INTO PRODUTO(NOME, PRECO, CATEGORIA_ID) VALUES ('HOT DOG', 12.00, 1);
INSERT INTO PRODUTO(NOME, PRECO, CATEGORIA_ID) VALUES ('MISTO QUENTE', 12.00, 1);
INSERT INTO PRODUTO(NOME, PRECO, CATEGORIA_ID) VALUES ('PRENSADO DE CARNE', 14.00, 1);
INSERT INTO PRODUTO(NOME, PRECO, CATEGORIA_ID) VALUES ('PRENSADO DE CARNE DUPLO', 15.00, 1);
INSERT INTO PRODUTO(NOME, PRECO, CATEGORIA_ID) VALUES ('PRENSADO DE CARNE COM BACON', 15.00, 1);
INSERT INTO PRODUTO(NOME, PRECO, CATEGORIA_ID) VALUES ('PRENSADO DE FRANGO', 14.00, 1);
INSERT INTO PRODUTO(NOME, PRECO, CATEGORIA_ID) VALUES ('PRENSADO DE FRANGO COM CATUPIRY', 15.00, 1);
INSERT INTO PRODUTO(NOME, PRECO, CATEGORIA_ID) VALUES ('PRENSADO DE FRANGO DUPLO', 15.00, 1);
INSERT INTO PRODUTO(NOME, PRECO, CATEGORIA_ID) VALUES ('PRENSADO DE FRANGO COM BACON', 15.00, 1);
INSERT INTO PRODUTO(NOME, PRECO, CATEGORIA_ID) VALUES ('X-BACON', 16.50, 1);
INSERT INTO PRODUTO(NOME, PRECO, CATEGORIA_ID) VALUES ('X-CALABRESA', 16.50, 1);
INSERT INTO PRODUTO(NOME, PRECO, CATEGORIA_ID) VALUES ('X-BURGUER', 15.00, 1);
INSERT INTO PRODUTO(NOME, PRECO, CATEGORIA_ID) VALUES ('X-CRISPINZINHO', 15.00, 1);
INSERT INTO PRODUTO(NOME, PRECO, CATEGORIA_ID) VALUES ('X-BACONLEZA', 19.00, 1);
INSERT INTO PRODUTO(NOME, PRECO, CATEGORIA_ID) VALUES ('X-EGG', 19.00, 1);
INSERT INTO PRODUTO(NOME, PRECO, CATEGORIA_ID) VALUES ('X-CRISPIN', 22.00, 1);
INSERT INTO PRODUTO(NOME, PRECO, CATEGORIA_ID) VALUES ('X-FILÉ MIGNON', 25.00, 1);
INSERT INTO PRODUTO(NOME, PRECO, CATEGORIA_ID) VALUES ('X-FILÉ DE FRANGO', 25.00, 1);
INSERT INTO PRODUTO(NOME, PRECO, CATEGORIA_ID) VALUES ('BIG BURGUER', 15.00, 2);
INSERT INTO PRODUTO(NOME, PRECO, CATEGORIA_ID) VALUES ('BIG SALADA', 17.00, 2);
INSERT INTO PRODUTO(NOME, PRECO, CATEGORIA_ID) VALUES ('BIG BACON', 18.00, 2);
INSERT INTO PRODUTO(NOME, PRECO, CATEGORIA_ID) VALUES ('BIG EGG', 18.00, 2);
INSERT INTO PRODUTO(NOME, PRECO, CATEGORIA_ID) VALUES ('BIG ESPECIAL', 19.00, 2);
INSERT INTO PRODUTO(NOME, PRECO, CATEGORIA_ID) VALUES ('BIG FILÉ MIGNON', 22.00, 2);
INSERT INTO PRODUTO(NOME, PRECO, CATEGORIA_ID) VALUES ('X-COSTELA DORITOS', 25.00, 2);
INSERT INTO PRODUTO(NOME, PRECO, CATEGORIA_ID) VALUES ('X-COSTELA BACON', 25.00, 2);
INSERT INTO PRODUTO(NOME, PRECO, CATEGORIA_ID) VALUES ('X-COSTELA CALABRESA', 25.00, 2);
INSERT INTO PRODUTO(NOME, PRECO, CATEGORIA_ID) VALUES ('BATATA COM QUEIJO E BACON', 18.00, 3);
INSERT INTO PRODUTO(NOME, PRECO, CATEGORIA_ID) VALUES ('BATATA COM CHEDDAR E BACON', 20.00, 3);
INSERT INTO PRODUTO(NOME, PRECO, CATEGORIA_ID) VALUES ('BATATA COM QUEIJO', 15.00, 3);
INSERT INTO PRODUTO(NOME, PRECO, CATEGORIA_ID) VALUES ('BATATA COM BACON', 15.00, 3);
INSERT INTO PRODUTO(NOME, PRECO, CATEGORIA_ID) VALUES ('CALABRESA COM CEBOLA', 20.00, 3);
INSERT INTO PRODUTO(NOME, PRECO, CATEGORIA_ID) VALUES ('FILÉ DE TILAPIA', 25.00, 3);
INSERT INTO PRODUTO(NOME, PRECO, CATEGORIA_ID) VALUES ('FRANGO FRITO', 20.00, 3);
INSERT INTO PRODUTO(NOME, PRECO, CATEGORIA_ID) VALUES ('TORRESMO', 20.00, 3);
INSERT INTO PRODUTO(NOME, PRECO, CATEGORIA_ID) VALUES ('POLENTA', 20.00, 3);
INSERT INTO PRODUTO(NOME, PRECO, CATEGORIA_ID) VALUES ('COMBO 01', 30.00, 4);
INSERT INTO PRODUTO(NOME, PRECO, CATEGORIA_ID) VALUES ('COMBO 02', 30.00, 4);
INSERT INTO PRODUTO(NOME, PRECO, CATEGORIA_ID) VALUES ('SUCO DE LARANJA', 10.00, 5);
INSERT INTO PRODUTO(NOME, PRECO, CATEGORIA_ID) VALUES ('SUCO DE MARACUJÁ', 10.00, 5);
INSERT INTO PRODUTO(NOME, PRECO, CATEGORIA_ID) VALUES ('SUCO DE ABACAXI', 10.00, 5);
INSERT INTO PRODUTO(NOME, PRECO, CATEGORIA_ID) VALUES ('SUCO DE ABACAXI COM HORTELÃ', 10.00, 5);
INSERT INTO PRODUTO(NOME, PRECO, CATEGORIA_ID) VALUES ('SUCO DE LIMÃO', 10.00, 5);
INSERT INTO PRODUTO(NOME, PRECO, CATEGORIA_ID) VALUES ('SUCO DE MORANGO', 10.00, 5);
INSERT INTO PRODUTO(NOME, PRECO, CATEGORIA_ID) VALUES ('REFRIGERANTE LATA 350ML', 4.00, 6);
INSERT INTO PRODUTO(NOME, PRECO, CATEGORIA_ID) VALUES ('FANTA', 4.00, 6);
INSERT INTO PRODUTO(NOME, PRECO, CATEGORIA_ID) VALUES ('COCA', 4.00, 6);
INSERT INTO PRODUTO(NOME, PRECO, CATEGORIA_ID) VALUES ('GUARANÁ', 4.00, 6);
INSERT INTO PRODUTO(NOME, PRECO, CATEGORIA_ID) VALUES ('COCA-COLA 600ML', 5.00, 6);
INSERT INTO PRODUTO(NOME, PRECO, CATEGORIA_ID) VALUES ('COCA-COLA 1L', 6.00, 6);
INSERT INTO PRODUTO(NOME, PRECO, CATEGORIA_ID) VALUES ('COCA-COLA 2L', 10.00, 6);
INSERT INTO PRODUTO(NOME, PRECO, CATEGORIA_ID) VALUES ('TUBAÍNA 600ML', 3.50, 6);
INSERT INTO PRODUTO(NOME, PRECO, CATEGORIA_ID) VALUES ('TUBAÍNA 2L', 6.00, 6);
INSERT INTO PRODUTO(NOME, PRECO, CATEGORIA_ID) VALUES ('SUCO PRATS 350ML', 4.50, 5);
INSERT INTO PRODUTO(NOME, PRECO, CATEGORIA_ID) VALUES ('SUCO PRATS 1L', 9.00, 5);
INSERT INTO PRODUTO(NOME, PRECO, CATEGORIA_ID) VALUES ('SKOL LATA 350ML', 4.00, 6);

-- CLIENTES

INSERT INTO CLIENTE(NOME,TELEFONE, CPF, ENDERECO, NUMERO, CIDADE_ID ) VALUES ('DIOGO MENESES DE FRANÇA', "44991162891", '12345678910', 'RUA INDAIAL ', '1230', 1);
INSERT INTO CLIENTE(NOME,TELEFONE, CPF, ENDERECO, NUMERO, CIDADE_ID ) VALUES ('CARLOS EDUARDO DE FRANÇA', "44991768883", '12345678911', 'RUA MATO GROSSO', '1050', 1);
INSERT INTO CLIENTE(NOME,TELEFONE, CPF, ENDERECO, NUMERO, CIDADE_ID ) VALUES ('ARACELES DE MENESES', "18988022202", '12345678912', 'RUA DOM PEDRO I', '70 C', 10);
INSERT INTO CLIENTE(NOME,TELEFONE, CPF, ENDERECO, NUMERO, CIDADE_ID ) VALUES ('ANDRÉ LUIZ DE ALMEIDA', "47991584678", '12345678913', 'RUA PERNAMBUCO', '257', 7);
INSERT INTO CLIENTE(NOME,TELEFONE, CPF, ENDERECO, NUMERO, CIDADE_ID ) VALUES ('JOÃO DOS SANTOS', "11994755812", '12345678914', 'RUA SERGIPE', '479', 9);
INSERT INTO CLIENTE(NOME,TELEFONE, CPF, ENDERECO, NUMERO, CIDADE_ID ) VALUES ('IRENE FERRAZ', "11987541759", '12345678915', 'AVENIDA JOSÉ BONIFÁCIO', '1630', 9);
INSERT INTO CLIENTE(NOME,TELEFONE, CPF, ENDERECO, NUMERO, CIDADE_ID ) VALUES ('ROSA MARIA DOS SANTOS', "1154574832", '12345678916', 'RUA SANTO ANTONIO', '1326', 9);

-- CRIANDO VENDAS

-- DIOGO COMPROU 2 HOT DOG E UMA COCA 600ML
INSERT INTO VENDA(CLIENTE_ID) VALUES (1);
INSERT INTO ITEM_VENDA(PRODUTO_ID, PRECO_UNITARIO, QUANTIDADE, VENDA_ID) VALUES (1, 13.00, 2, 1);
INSERT INTO ITEM_VENDA(PRODUTO_ID, PRECO_UNITARIO, QUANTIDADE, VENDA_ID) VALUES (49, 7.50, 1, 1);

-- CARLOS EDUARDO COMPROU 1 X-BACON E UMA COCA 2L
INSERT INTO VENDA(CLIENTE_ID) VALUES (2);
INSERT INTO ITEM_VENDA(PRODUTO_ID, PRECO_UNITARIO, QUANTIDADE, VENDA_ID) VALUES (10, 18.50, 1, 2);
INSERT INTO ITEM_VENDA(PRODUTO_ID, PRECO_UNITARIO, QUANTIDADE, VENDA_ID) VALUES (51, 12.00, 1, 2);

-- ARACELES COMPROU 2 X-BACON E 1 COCA GARRAFINHA
INSERT INTO VENDA(CLIENTE_ID) VALUES (3);
INSERT INTO ITEM_VENDA(PRODUTO_ID, PRECO_UNITARIO, QUANTIDADE, VENDA_ID) VALUES (10, 18.50, 2, 3);
INSERT INTO ITEM_VENDA(PRODUTO_ID, PRECO_UNITARIO, QUANTIDADE, VENDA_ID) VALUES (47, 6.00, 1, 3);

-- IRENE COMPROU UMA PORÇÃO DE BATATA COM QUEIJO E BACON E 2 CERVEJAS SKOL LATA
INSERT INTO VENDA(CLIENTE_ID) VALUES (6);
INSERT INTO ITEM_VENDA(PRODUTO_ID, PRECO_UNITARIO, QUANTIDADE, VENDA_ID) VALUES (28, 25.00, 1, 4);
INSERT INTO ITEM_VENDA(PRODUTO_ID, PRECO_UNITARIO, QUANTIDADE, VENDA_ID) VALUES (56, 5.00, 2, 4);

-- JOÃO COMPROU UMA PORÇÃO DE FILÉ DE TILÁPIA E 3 CERVEJAS SKOL LATA
INSERT INTO VENDA(CLIENTE_ID) VALUES (5);
INSERT INTO ITEM_VENDA(PRODUTO_ID, PRECO_UNITARIO, QUANTIDADE, VENDA_ID) VALUES (33, 23.00, 1, 5);
INSERT INTO ITEM_VENDA(PRODUTO_ID, PRECO_UNITARIO, QUANTIDADE, VENDA_ID) VALUES (56, 5.00,  3, 5);

-- ANDRÉ LUIZ COMPROU 2 X-CALABRESA E 1 COCA 2L
INSERT INTO VENDA(CLIENTE_ID) VALUES (4);
INSERT INTO ITEM_VENDA(PRODUTO_ID, PRECO_UNITARIO, QUANTIDADE, VENDA_ID) VALUES (11, 18.50,2, 6);
INSERT INTO ITEM_VENDA(PRODUTO_ID, PRECO_UNITARIO, QUANTIDADE, VENDA_ID) VALUES (51, 12.00, 1, 6);

-- TRIGGER QUE NÃO PERMITE QUE O PRODUTO SEJA VENDIDO ABAIXO DE UMA MARGEM DE LUCRO DETERMINADA PELA REGRA DE NEGOCIO

DELIMITER //
CREATE TRIGGER CONTROLE_PRECO_VENDA
BEFORE INSERT ON ITEM_VENDA
FOR EACH ROW
BEGIN
    DECLARE PRECO_COMPRA DECIMAL(10,2);
    SELECT PRECO INTO PRECO_COMPRA FROM PRODUTO WHERE PRODUTO.ID = NEW.PRODUTO_ID;
    IF PRECO_COMPRA > NEW.PRECO_UNITARIO THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = "NÃO AUTORIZADO, PREÇO DE VENDA ABAIXO DA MARGEM DE LUCRO!";
        DELETE FROM VENDA WHERE ID = NEW.VENDA_ID;
    END IF;
END;
// DELIMITER ;

-- TESTE DA TRIGGER DE CONTROLE DE PREÇO DE VENDA
/*
INSERT INTO VENDA(CLIENTE_ID) VALUES (4);
INSERT INTO ITEM_VENDA(PRODUTO_ID, PRECO_UNITARIO, QUANTIDADE, VENDA_ID) VALUES (11, 10.50,2, 6);
INSERT INTO ITEM_VENDA(PRODUTO_ID, PRECO_UNITARIO, QUANTIDADE, VENDA_ID) VALUES (51, 7.00, 1, 6);
*/

-- TRIGGER QUE VERIFICA SE O NÚMERO DE CARACTERES INSERIDOS É DE UM CPF VÁLIDO COM 11 DÍGITOS

DELIMITER //
CREATE TRIGGER VALIDA_CPF_CLIENTE
BEFORE INSERT ON CLIENTE
FOR EACH ROW
BEGIN
    IF LENGTH(NEW.CPF) < 11 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = "O NÚMERO DIGITADO NÃO É UM CPF VÁLIDO";
    END IF;
END;
//
DELIMITER ;

-- TESTE DA TIGGER VALIDA_CPF_CLIENTE

-- INSERT INTO CLIENTE(NOME, TELEFONE, CPF, ENDERECO, NUMERO, CIDADE_ID ) VALUES ('RODRIGO DOS SANTOS', "44991164691", '12345695', 'RUA TAMANDARÉ ', '120', 1);


-- TRIGGER QUE MONITORA QUANDO UM CLIENTE É COLOCADO COMO INATIVO

CREATE TABLE CONTROLE_CLIENTES_INATIVOS(
ID INT NOT NULL AUTO_INCREMENT
,NOME VARCHAR(100) NOT NULL
,CLIENTE_ID INT NOT NULL
,DATA_INATIVACAO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
, CONSTRAINT PK_INATIVOS PRIMARY KEY CONTROLE_CLIENTES_INATIVOS(ID)
);

DELIMITER //
CREATE TRIGGER INFORMA_CLIENTE_INATIVO
AFTER UPDATE ON CLIENTE
FOR EACH ROW
BEGIN
    IF (NEW.ATIVO = "N") THEN
        INSERT INTO CONTROLE_CLIENTES_INATIVOS (NOME, CLIENTE_ID) VALUES (NEW.NOME, NEW.ID);
    END IF;
END;
//
DELIMITER ;

-- TESTE DA TRIGGER INFORMA_CLIENTE_INATIVO

UPDATE CLIENTE SET ATIVO = 'N' WHERE ID = 2;

SELECT * FROM CONTROLE_CLIENTES_INATIVOS;

select * from produto where id = 4;


